services:
    symbio_fulltext_search:
        class: %symbio_fulltext_search.class%
        arguments:
            - @kernel
            - @symbio_fulltext_search.index_manager
            - %symbio_fulltext_search.terms_per_query_limit%

    symbio_fulltext_search.crawler:
        class: %symbio_fulltext_search.crawler.class%
        arguments:
            - @service_container
            - @symbio_fulltext_search.index_manager

    symbio_fulltext_search.index_manager:
        class: Symbio\FulltextSearchBundle\Service\IndexManager
        arguments:
            - @kernel
            - @ivory_lucene_search

    symbio_fulltext_search.events_manager:
        class: Symbio\FulltextSearchBundle\Event\EventsManager
        arguments:
            - @?symbio_fulltext_search.event.page_extracted

    symbio_fulltext_search.provider.html:
        class: %symbio_fulltext_search.provider.html.class%
        arguments:
            - @symbio_fulltext_search.events_manager

    symbio_fulltext_search.provider.pdf:
        class: %symbio_fulltext_search.provider.pdf.class%
        arguments:
            - @symbio_fulltext_search.events_manager

    symbio_fulltext_search.twig_extension:
        class: Symbio\FulltextSearchBundle\Twig\FulltextSearchExtension
        public: false
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    data_collector.search:
        class: Symbio\FulltextSearchBundle\Profiler\DataCollector\SearchDataCollector
        arguments:
            - @symbio_fulltext_search
        tags:
            - { name: data_collector, template: "SymbioFulltextSearchBundle:Profiler:search.html.twig", id: "symbio_fulltext_search" }
